# Site settings
title: Scott Ogle
email: scottogle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects, software thinking, data visualization, news hacking and assorted writings.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.scottogle.net" # the base hostname & protocol for your site
permalink: /:title.html

twitter_username: scogle
#github_username:  scogle

header_img: img/cabbage.jpg

# Build settings
markdown: kramdown
